# Generated by Django 4.1.7 on 2023-03-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='notesapp/static/images/default.jpg', null=True, upload_to='images'),
        ),
    ]
